### ISSUE TITLE
(Suggestion) Fix laggy UI

### ISSUE THREAD

**Issue by ngxson** [hemantsachdeva/dt_laurel_sprout_r#3]
Hi,

I've just discovered that due to low CPU frequency, the UI is laggy especially when there is no task on the background. The main cause is because the "schedutil" governor refuses to raise the frequency.

I've tried adding this in the end of [`init.qcom.post_boot.sh`](https://github.com/HemantSachdeva/device_xiaomi_laurel_sprout/blob/snow/rootdir/etc/init.qcom.post_boot.sh) and the issue was fixed: https://github.com/ngxson/device_xiaomi_laurel_sprout/commit/dfc97b1614339aa9be1e084c84beb2b9bcebdd25

Please note that I only use `ondemand` governor for little cores, so there won't be a big impact on battery life.

Thank you.

**Comment by HemantSachdeva** [comment]
Thanks, will look give it a try once server is up.

Also #2 would be enabled now from rom side as new blur feature is implemented now.
